version: '2'

services:
  tarantool:
    container_name: tarantool_ski_resort
    image: tarantool/tarantool:2.8
    command: tarantool /usr/local/share/tarantool/app.init.lua
    ports:
      - 3301:3301
    volumes:
      - /mnt/c/Users/alena/Desktop/7_sem/testing_and_debugging/SkiResort/tarantool/app:/usr/local/share/tarantool
      - /mnt/c/Users/alena/Desktop/7_sem/testing_and_debugging/SkiResort/tarantool/data:/var/lib/tarantool