version: '3.5'

services:

  bl:
    image: bl
    build:
      context: .
      dockerfile: Dockerfile

  bl-tests:
    image: bl-tests
    build:
      context: .
      dockerfile: Dockerfile      
      target: test