name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
        
  runAll:
    name: Build
    runs-on: ubuntu-latest
    #runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
     
    # - name: tmp2
      # run: pwd # home\runner\work\BMSTU_7sem_testing_and_debugging\BMSTU_7sem_testing_and_debugging\SkiResort
      # working-directory: SkiResort
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SkiResort
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: SkiResort
    
    - name: Run All Tests
      run: ./run_all_tests.sh
      working-directory: .

  #unitTesting:
    #name: Unit Testing
    #needs: build
    - name: Run BL Unit Tests
      run: dotnet test BL.Tests --no-build --verbosity normal #normal #detailed
      working-directory: SkiResort
     
    - name: Start Tarantool In Docker
      run: docker-compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml up -d
      working-directory: SkiResort
      
      
    - name: Run AccessToDB Unit Tests
      run: dotnet test AccessToDB.Tests --no-build --verbosity normal 
      working-directory: SkiResort
      
    - name: Stop Tarantool In Docker
      run: docker compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml down
      working-directory: SkiResort/tarantool
      
    #integrationTesting:
    - name: Start Tarantool In Docker
      run: docker-compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml up -d
      working-directory: SkiResort
      
    - name: Run Integration Tests
      run: dotnet test IntegrationTests --no-build --verbosity normal 
      working-directory: SkiResort
      
    - name: Stop Tarantool In Docker
      run: docker compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml down
      working-directory: SkiResort/tarantool
      
      
    #e2eTesting:
    - name: Start Tarantool In Docker
      run: docker-compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml up -d
      working-directory: SkiResort
      
    - name: Run E2E Tests
      run: dotnet test E2ETests --no-build --verbosity normal 
      working-directory: SkiResort
      
    - name: Stop Tarantool In Docker
      run: docker compose -f /home/runner/work/BMSTU_7sem_testing_and_debugging/BMSTU_7sem_testing_and_debugging/SkiResort/tarantool/docker-compose-git.yml down
      working-directory: SkiResort/tarantool
      
      
    # - name: Generate BL Unit Tests report
      # run: npm install -g allure-commandline --save-dev && allure generate BL.Tests/bin/Debug/net6.0/allure-results AccessToDB.Tests/bin/Debug/net6.0/allure-results --clean -o allure-report-for-unit-tests # && allure open allure-report-for-unit-tests
      # working-directory: SkiResort
      
    # - name: Generate AccessToDB Unit Tests report
      # run: npm install -g allure-commandline --save-dev && allure generate BL.Tests/bin/Debug/net6.0/allure-results AccessToDB.Tests/bin/Debug/net6.0/allure-results --clean -o allure-report-for-unit-tests # && allure open allure-report-for-unit-tests
      # working-directory: SkiResort


# uses позволяет переиспользовать другие экшены  
# При помощи with мы можем указать параметры с которыми запускаем действие, по сути это аргументы, которые будут передаваться в экшен.